// ── Panel content renderers ──
function renderPanelContent(role, tab) {
  const zones=DB.zones||[],resources=DB.resources||[],reports=DB.recent_reports||[];
  const hospitals=DB.hospitals||[],roadBlocks=DB.active_road_blocks||[];
  const incidents=DB.active_incidents||DB.fire_incidents||DB.incoming_medical_incidents||[];
  const dispatches=DB.active_dispatches||[],alerts=DB.recent_alerts||DB.alerts||[];
  if(role==='gov'){
    if(tab==='Overview') return `<div class="slabel">ZONE SEVERITY</div>${zoneRowsHTML(zones)}<div class="slabel" style="margin-top:14px">DISPATCHES (${dispatches.length})</div>${dispatches.length?dispatches.map(d=>`<div class="report-card"><div class="rc-head"><span class="rc-loc">${d.resource_type}→${d.target_ward}</span><span class="rc-time">${ago(d.dispatched_at)}</span></div><div class="rc-body">${d.reason}</div></div>`).join(''):'<div style="color:var(--txt3);font-size:11px">No active dispatches</div>'}`;
    if(tab==='Reports') return `<div class="slabel">CITIZEN REPORTS (${reports.length})</div>${reports.map(r=>`<div class="report-card"><div class="rc-head"><span class="rc-loc">${r.ward_name}</span><span class="rc-time">${ago(r.reported_at)}</span></div><div class="rc-body">${r.description}</div><div style="display:flex;gap:6px"><span class="rc-badge" style="background:${r.verified?'#0a2018':'#2a0d0d'};color:${r.verified?'#4ade80':'#f87171'}">${r.verified?'✓ Verified':'⚠ Unverified'}</span>${r.gemini_depth_estimate?`<span class="rc-depth-chip" style="background:var(--bg3);color:var(--txt2)">~${r.gemini_depth_estimate}m</span>`:''}</div></div>`).join('')}`;
    if(tab==='Resources') return `<div class="slabel">ALL RESOURCES</div>${resources.map(r=>resRowHTML(r)).join('')}`;
    if(tab==='Triage') return `<div class="slabel">TRIAGE COMMANDER</div><button class="action-btn primary" onclick="runTriage()"><i class="ti ti-drone"></i><div><div>Run Triage Commander</div><div class="ab-sub">AI dispatches to critical zones</div></div></button><div id="triageResult"></div>`;
  }
  if(role==='police'){
    if(tab==='Zones') return `<div class="slabel">FLOOD ZONES</div>${zoneRowsHTML(zones)}`;
    if(tab==='Road Blocks') return `<div class="slabel">ROAD BLOCKS (${roadBlocks.length})</div>${roadBlocks.map(b=>`<div class="res-row"><div class="res-icon" style="background:#0d2a1a;color:#22c55e"><i class="ti ti-barrier-block" style="font-size:14px"></i></div><div style="flex:1"><div class="res-name">${b.road_name}</div><div class="res-sub">${b.reason} · ${b.depth_at_block}m</div></div><span class="res-status" style="background:#0a201818;color:${statusColor(b.status)}">${b.status.toUpperCase()}</span></div>`).join('')}`;
    if(tab==='Incidents') return `<div class="slabel">INCIDENTS</div>${incidents.map(i=>`<div class="report-card"><div class="rc-head"><span class="rc-loc">${i.location_name}</span><span class="rc-badge" style="background:#2a0d0d18;color:${riskColor(i.severity)}">${i.severity}</span></div><div class="rc-body">${i.incident_type.replace(/_/g,' ')}</div></div>`).join('')||'<div style="color:var(--txt3);font-size:11px">No incidents</div>'}`;
    if(tab==='Alerts') return `<div class="slabel">ALERTS</div>${renderAlerts(alerts)}`;
  }
  if(role==='hospital'){
    if(tab==='Capacity') return `<div class="slabel">BED AVAILABILITY</div>${hospitals.map(h=>{const ws=[{n:'General',a:h.general_beds_available,t:h.general_beds_total},{n:'ICU',a:h.icu_beds_available,t:h.icu_beds_total},{n:'Emergency',a:h.emergency_beds_available,t:h.emergency_beds_total}];return`<div style="margin-bottom:14px"><div style="font-size:12px;font-weight:500;color:var(--txt);margin-bottom:8px">${h.hospital_name}</div>${ws.map(w=>{const p=(w.a/w.t*100).toFixed(0),c=p<30?'#f87171':p<60?'#fb923c':'#4ade80';return`<div style="margin-bottom:6px"><div style="display:flex;justify-content:space-between;margin-bottom:3px"><span style="font-size:10px;color:var(--txt2)">${w.n}</span><span style="font-size:10px;font-family:var(--mono);color:${c}">${w.a}/${w.t}</span></div><div style="height:4px;background:var(--bg3);border-radius:2px;overflow:hidden"><div style="height:100%;width:${p}%;background:${c};border-radius:2px"></div></div></div>`}).join('')}<div style="font-size:9px;color:var(--txt3)">Blood O+: ${h.blood_o_positive} · IV: ${h.iv_fluids_bags} · Tetanus: ${h.tetanus_doses}</div></div>`}).join('')}`;
    if(tab==='Resources'){const a=(DB.ambulances||resources).filter(r=>r.resource_type==='ambulance');return`<div class="slabel">AMBULANCES</div>${a.map(r=>resRowHTML(r,'ti-ambulance')).join('')}`;}
    if(tab==='Incidents') return`<div class="slabel">MEDICAL</div>${incidents.map(i=>`<div class="report-card"><div class="rc-head"><span class="rc-loc">${i.location_name||''}</span></div><div class="rc-body">${(i.incident_type||'').replace(/_/g,' ')}</div></div>`).join('')||'<div style="color:var(--txt3);font-size:11px">None</div>'}`;
  }
  if(role==='fire'){
    if(tab==='Incidents') return`<div class="slabel">FIRE INCIDENTS</div>${incidents.map(i=>`<div class="report-card"><div class="rc-head"><span class="rc-loc">${i.location_name||''}</span><span class="rc-badge" style="background:#2a120018;color:#fb923c">${i.status}</span></div><div class="rc-body">${(i.incident_type||'').replace(/_/g,' ')}</div></div>`).join('')||'<div style="color:var(--txt3);font-size:11px">None</div>'}`;
    if(tab==='Resources'){const f=DB.fire_resources||resources.filter(r=>r.owner_role==='fire');return`<div class="slabel">FLEET</div>${f.map(r=>resRowHTML(r)).join('')}`;}
    if(tab==='Dispatches') return`<div class="slabel">DISPATCHES</div>${dispatches.map(d=>`<div class="report-card"><div class="rc-head"><span class="rc-loc">${d.resource_type}→${d.target_ward}</span><span class="rc-time">ETA ${d.eta_minutes}m</span></div><div class="rc-body">${d.reason}</div></div>`).join('')||'<div style="color:var(--txt3);font-size:11px">None</div>'}`;
  }
  if(role==='citizen'){
    const z=DB.zone||zones[0]||{};
    if(tab==='My Area') return`${z.risk_level==='critical'||z.risk_level==='severe'?`<div style="background:#2a0d0d;border:1px solid #7f1d1d;border-radius:8px;padding:12px;margin-bottom:14px"><div style="font-size:12px;font-weight:500;color:#f87171;margin-bottom:4px"><i class="ti ti-alert-triangle" style="font-size:14px;margin-right:6px"></i>Flood warning</div><div style="font-size:11px;color:#fca5a5;line-height:1.6">${z.ward_name||''}: <strong>${z.depth_meters||0}m</strong> depth predicted.</div></div>`:''}<div class="slabel">STATUS</div>${[{l:'Zone',v:z.ward_name||'--',c:riskColor(z.risk_level)},{l:'Depth',v:(z.depth_meters||0)+'m',c:riskColor(z.risk_level)},{l:'Access',v:((z.road_accessibility||0)*100).toFixed(0)+'%',c:'#a78bfa'}].map(r=>`<div style="display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid var(--border)"><span style="font-size:11px;color:var(--txt3)">${r.l}</span><span style="font-size:11px;font-family:var(--mono);color:${r.c}">${r.v}</span></div>`).join('')}<div class="slabel" style="margin-top:12px">SHELTERS</div>${(DB.evacuation_shelters||[]).map(s=>`<div class="res-row"><div class="res-icon" style="background:#1a1040;color:#a78bfa"><i class="ti ti-home" style="font-size:14px"></i></div><div style="flex:1"><div class="res-name">${s.name}</div></div></div>`).join('')}`;
    if(tab==='Alerts') return`<div class="slabel">ALERTS</div>${renderAlerts(alerts)}`;
    if(tab==='Report') return`<div class="slabel">REPORT FLOOD</div><textarea id="reportDesc" rows="3" style="width:100%;background:var(--bg2);border:1px solid var(--border);border-radius:7px;padding:8px;font-size:11px;color:var(--txt);font-family:var(--sans);resize:none;margin-bottom:8px" placeholder="Describe flood..."></textarea><div style="display:flex;gap:8px;margin-bottom:10px"><div style="flex:1"><div style="font-size:10px;color:var(--txt3);margin-bottom:4px">Lat</div><input id="reportLat" type="number" step="0.001" value="12.925" style="width:100%;background:var(--bg2);border:1px solid var(--border);border-radius:7px;padding:6px;font-size:11px;color:var(--txt);font-family:var(--mono)"></div><div style="flex:1"><div style="font-size:10px;color:var(--txt3);margin-bottom:4px">Lng</div><input id="reportLng" type="number" step="0.001" value="77.668" style="width:100%;background:var(--bg2);border:1px solid var(--border);border-radius:7px;padding:6px;font-size:11px;color:var(--txt);font-family:var(--mono)"></div></div><button class="action-btn primary" style="justify-content:center" onclick="submitReport()"><i class="ti ti-send" style="font-size:14px"></i>Submit Report</button><div id="reportStatus" style="margin-top:8px;font-size:11px"></div>`;
  }
  return '';
}
function renderAlerts(a){return a.map(x=>{const c={evacuation:'#f87171',warning:'#fb923c',info:'#3b7bff',all_clear:'#4ade80'}[x.severity]||'#94a3b8';return`<div class="alert-item"><div class="alert-dot-wrap"><div class="alert-type-dot" style="background:${c}"></div></div><div><div class="alert-title">${x.message||x.ward_name}</div><div class="alert-meta">${x.channel||'system'} · ${x.recipients_count||0} rcpt · ${ago(x.sent_at)}</div></div></div>`}).join('')||'<div style="color:var(--txt3);font-size:11px">No alerts</div>';}
async function submitReport(){const d=document.getElementById('reportDesc').value;if(!d)return;const el=document.getElementById('reportStatus');el.innerHTML='<span style="color:#fb923c">Submitting...</span>';try{const r=await fetch(`${API}/api/citizen-reports/quick`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({description:d,lat:parseFloat(document.getElementById('reportLat').value),lng:parseFloat(document.getElementById('reportLng').value)})});const j=await r.json();el.innerHTML=`<span style="color:#4ade80">✓ ${j.report_id} saved to ${j.zone_id}</span>`;document.getElementById('reportDesc').value='';}catch(e){el.innerHTML='<span style="color:#f87171">Failed</span>';}}
async function runTriage(){const el=document.getElementById('triageResult');el.innerHTML='<div style="color:#fb923c;font-size:11px">Running...</div>';try{const r=await fetch(`${API}/api/triage/run`,{method:'POST'});const d=await r.json();el.innerHTML=`<div class="log-item" style="border-left-color:#4ade80;background:#0a201818;margin-top:8px"><div class="log-tag" style="color:#4ade80">COMPLETE</div><div class="log-text">${d.session_id} · Dispatches:${d.dispatch_count} · Pop:${d.population_covered.toLocaleString()}</div></div>`;}catch(e){el.innerHTML='<div style="color:#f87171;font-size:11px">Failed</div>';}}
function renderBottomBar(){const s=DB.summary||{};const m={gov:[{v:s.total_zones||0,c:'#f87171',l:'Zones'},{v:(s.total_population_affected||0).toLocaleString(),c:'#fb923c',l:'At risk'},{v:s.available_resources||0,c:'#4ade80',l:'Resources'},{v:s.active_dispatches||0,c:'#3b7bff',l:'Dispatches'}],police:[{v:s.active_blocks||0,c:'#f87171',l:'Blocked'},{v:s.active_incidents||0,c:'#fb923c',l:'Incidents'},{v:s.available_units||0,c:'#4ade80',l:'Units'}],hospital:[{v:s.total_beds_available||0,c:'#f87171',l:'Beds'},{v:s.icu_available||0,c:'#fb923c',l:'ICU'},{v:s.ambulances_available||0,c:'#4ade80',l:'Ambulances'}],fire:[{v:s.active_incidents||0,c:'#fb923c',l:'Incidents'},{v:s.available_engines||0,c:'#4ade80',l:'Engines'}],citizen:[{v:((DB.zone||{}).risk_level||'--').toUpperCase(),c:'#f87171',l:'Risk'}]}[currentRole]||[];['bm1','bm2','bm3','bm4'].forEach((id,i)=>{const el=document.getElementById(id);el.innerHTML=m[i]?`<span class="bm-val" style="color:${m[i].c}">${m[i].v}</span><span class="bm-lbl">${m[i].l}</span>`:''});}
async function setRole(role){currentRole=role;currentTab=0;const r=ROLES[role];document.documentElement.style.setProperty('--role-color',r.color);document.documentElement.style.setProperty('--role-bg',r.bg);document.documentElement.style.setProperty('--role-border',r.border);document.getElementById('logoMark').style.background=r.color;document.getElementById('roleDot').style.background=r.color;document.getElementById('roleBtnLabel').textContent=r.label;document.getElementById('avatarEl').textContent=r.avatar;document.getElementById('avatarEl').style.background=r.bg;document.getElementById('avatarEl').style.color=r.color;document.getElementById('rpRoleName').innerHTML=`<i class="ti ${r.icon}" style="font-size:15px"></i>${r.label}`;document.getElementById('rpRoleSub').textContent=r.sub;document.querySelectorAll('.role-option').forEach(el=>el.classList.remove('active'));document.getElementById('opt-'+role).classList.add('active');document.getElementById('roleDropdown').classList.remove('open');await fetchDash(role);renderMapZones();renderPanel();renderBottomBar();const p=document.getElementById('rPanel');p.classList.remove('switching');void p.offsetWidth;p.classList.add('switching');}
function renderPanel(){const r=ROLES[currentRole];document.getElementById('ptabs').innerHTML=r.tabs.map((t,i)=>`<div class="ptab${i===currentTab?' active':''}" onclick="switchTab(${i})">${t}</div>`).join('');document.getElementById('pbody').innerHTML=renderPanelContent(currentRole,r.tabs[currentTab]);}
function switchTab(i){currentTab=i;renderPanel();}
function toggleDropdown(){document.getElementById('roleDropdown').classList.toggle('open')}
document.addEventListener('click',e=>{if(!e.target.closest('.role-switcher'))document.getElementById('roleDropdown').classList.remove('open')});
function tick(){document.getElementById('clock').textContent=new Date().toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour12:false})+' IST'}
tick();setInterval(tick,1000);
setRole('gov');
